### ISSUE TITLE
Blowpipe ticks not being counted

### ISSUE THREAD

**Issue by graftss** [Chrisioman/PvMTickCounter#1]
Thank you for making this plugin, I've found it really useful!

When blowpiping, it seems that while the first attack counts as 2 attack ticks, all future attacks don't increase the tick count. I don't really understand why that's the case, but it looks like the [outdated plugin](https://github.com/winterdaze/tick-counter/blob/master/src/main/java/com/tickcounter/TickCounterPlugin.java#L44) had some extra blowpipe-specific state which might have been to fix this. I'm not sure though - just thought it might be relevant.

**Comment by Chrisioman** [comment]
Yes, I noticed this, I've corrected it and I've made a pull request to have it updated :). I believe it should be resolved soon.

https://github.com/runelite/plugin-hub/pull/3689

**Comment by graftss** [comment]
That's great, thanks for letting me know!
