### ISSUE TITLE
Blowpipe gives 4 ticks (expected 2)

### ISSUE THREAD

**Issue by lukechristy** [Chrisioman/PvMTickCounter#2]
If you blowpipe one time the counter will increment 2ticks, 2 times (for total 4 ticks). Expected that each blowpipe attack grants 2 ticks on the tracker

**Comment by Chrisioman** [comment]
Noted and just noticed the behaviour, will try to find a solution

**Comment by Chrisioman** [comment]
Issue should be resolved once the next commit goes through
